# kongyl/geoserver:2.22.4-gdal
FROM kongyl/gdal-java:3.2.2-11
LABEL author="kongyl"
LABEL email="kongyl@126.com"
LABEL version="2.22.4-gdal"
ADD geoserver-2.22.4.tar.gz /root
ENV GEOSERVER_HOME=/root/geoserver-2.22.4 GEOSERVER_DATA_DIR=/geoserver/data
ENV GDAL_DATA /usr/share/gdal
EXPOSE 8080
ENTRYPOINT ["/root/geoserver-2.22.4/bin/startup.sh"]
