# kongyl/geoserver:2.22.3-gdal
FROM kongyl/gdal-java:3.4.1-11
LABEL author="kongyl"
LABEL email="kongyl@126.com"
LABEL version="2.22.3-gdal"
ADD geoserver-2.22.3.tar.gz /root
ENV GEOSERVER_HOME=/root/geoserver-2.22.3 GEOSERVER_DATA_DIR=/geoserver/data
ENV GDAL_DATA /usr/share/gdal
EXPOSE 8080
ENTRYPOINT ["/root/geoserver-2.22.3/bin/startup.sh"]
