# kongyl/geoserver:2.22.0-gdal
FROM kongyl/gdal-java:3.5.1-11
LABEL author="kongyl"
LABEL email="kongyl@126.com"
LABEL version="2.22.0-gdal"
MAINTAINER kongyl
ADD geoserver-2.22.0.tar.gz /root
ENV GEOSERVER_HOME=/root/geoserver-2.22.0 GEOSERVER_DATA_DIR=/geoserver/data
ENV GDAL_DATA /usr/share/gdal # for geoserver gdal
EXPOSE 8080
WORKDIR /root/geoserver-2.22.0
ENTRYPOINT ["java", "-jar", "start.jar"]
