# kongyl/geoserver:2.22.2-gdal-hdfs
FROM kongyl/gdal-java:3.6.4-11-hdfs
LABEL author="kongyl"
LABEL email="kongyl@126.com"
LABEL version="2.22.2-gdal-hdfs"
ADD geoserver-2.22.2.tar.gz /root
ENV GEOSERVER_HOME=/root/geoserver-2.22.2 GEOSERVER_DATA_DIR=/geoserver/data
ENV GDAL_DATA /usr/share/gdal # for geoserver gdal
EXPOSE 8080
ENTRYPOINT ["/root/geoserver-2.22.2/bin/startup.sh"]
