# kongyl/geoserver:2.23.0-gdal-s3
FROM kongyl/gdal-java:3.4.1-11
LABEL author="kongyl"
LABEL email="kongyl@126.com"
LABEL version="2.23.0-gdal-s3"
MAINTAINER kongyl
ADD geoserver-2.23.0.tar.gz /root
ENV GEOSERVER_HOME=/root/geoserver-2.23.0 GEOSERVER_DATA_DIR=/geoserver/data
ENV GDAL_DATA /usr/share/gdal # for geoserver gdal
EXPOSE 8080
WORKDIR /root/geoserver-2.23.0/bin
ENTRYPOINT ["startup.sh"]
