FROM ubuntu:impish
LABEL author="kongyl"
LABEL email="kongyl@126.com"
LABEL version="14.0-3.1.4"
ADD jre-8u311-linux-x64.tar.gz /usr/local
ENV JAVA_HOME=/usr/local/jre1.8.0_311
ENV CLASSPATH=.:$JAVA_HOME/lib
ENV PATH=$PATH:$JAVA_HOME/bin
