# registry.cn-beijing.aliyuncs.com/kongyl/java:oracle-jre-1.8.0_381
FROM debian:bookworm-slim
LABEL author="kongyl"
LABEL email="kongyl@126.com"
LABEL version="oracle-jre-1.8.0_381"
ADD server-jre-8u381-linux-x64.tar.gz /usr/local
ENV JAVA_HOME=/usr/local/jdk1.8.0_381
ENV CLASSPATH=.:$JAVA_HOME/lib
ENV PATH=$PATH:$JAVA_HOME/bin
