# kongyl/java:openjdk-17.0.12-jdk-headless
FROM debian:bookworm
LABEL author="kongyl"
LABEL email="kongyl@126.com"
LABEL version="openjdk-17.0.12-jdk-headless"
RUN \
  #mv /etc/apt/sources.list /etc/apt/sources.list.bak && \
  #echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm main contrib non-free non-free-firmware" >>/etc/apt/sources.list && \
  #echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm-updates main contrib non-free non-free-firmware" >>/etc/apt/sources.list && \
  #echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm-backports main contrib non-free non-free-firmware" >>/etc/apt/sources.list && \
  #echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian-security bookworm-security main contrib non-free non-free-firmware" >>/etc/apt/sources.list && \
  apt-get update && \
  apt-get install -y --no-install-recommends openjdk-17-jdk-headless maven && \
  apt-get autoremove -y && \  
  apt-get clean && \
  rm -rf /var/cache/apt/* && \
  rm -rf /var/lib/apt/lists/*
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV CLASSPATH=.:$JAVA_HOME/lib
ENV PATH=$PATH:$JAVA_HOME/bin
