# oracle-jre-1.8.0_341
FROM ubuntu:jammy
LABEL author="kongyl"
LABEL email="kongyl@126.com"
LABEL version="oracle-jre-1.8.0_341"
ADD jre-8u341-linux-x64.tar.gz /usr/local
ENV JAVA_HOME=/usr/local/jre1.8.0_341
ENV CLASSPATH=.:$JAVA_HOME/lib
ENV PATH=$PATH:$JAVA_HOME/bin
