# kongyl/java:oracle-jre-1.8.0_371
FROM ubuntu:jammy
LABEL author="kongyl"
LABEL email="kongyl@126.com"
LABEL version="oracle-jre-1.8.0_371"
ADD server-jre-8u371-linux-x64.tar.gz /usr/local
ENV JAVA_HOME=/usr/local/jdk1.8.0_371
ENV CLASSPATH=.:$JAVA_HOME/lib
ENV PATH=$PATH:$JAVA_HOME/bin
