# docker.io/kongyl/java:openjdk-11.0.18-jre-headless-bullseye
FROM docker.io/library/debian:bullseye-slim
LABEL author="kongyl"
LABEL email="kongyl@126.com"
LABEL version="openjdk-11.0.18-jre-headless-bullseye"
RUN \
  mv /etc/apt/sources.list /etc/apt/sources.list.bak && \
  echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye main non-free contrib" >>/etc/apt/sources.list && \
  echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian-security/ bullseye-security main" >>/etc/apt/sources.list && \
  echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye-updates main non-free contrib" >>/etc/apt/sources.list && \
  echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye-backports main non-free contrib" >>/etc/apt/sources.list && \
  apt-get update && \
  apt-get install -y --no-install-recommends openjdk-11-jre-headless && \
  apt-get autoremove -y && \  
  apt-get clean && \
  rm -rf /var/cache/apt/* && \
  rm -rf /var/lib/apt/lists/*
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV CLASSPATH=.:$JAVA_HOME/lib
ENV PATH=$PATH:$JAVA_HOME/bin
