# kongyl/gdal-java:3.2.2-11-bullseye
FROM kongyl/java:openjdk-11.0.18-jre-headless-bullseye
LABEL author="kongyl"
LABEL email="kongyl@126.com"
LABEL version="3.2.2-11-bullseye"
RUN \
  mv /etc/apt/sources.list /etc/apt/sources.list.bak && \
  echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye main non-free contrib" >>/etc/apt/sources.list && \
  echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian-security/ bullseye-security main" >>/etc/apt/sources.list && \
  echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye-updates main non-free contrib" >>/etc/apt/sources.list && \
  echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye-backports main non-free contrib" >>/etc/apt/sources.list && \
  apt-get update && \
  apt-get install -y gdal-bin && \
  apt-get autoremove -y && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*
ADD libgdalalljni-3.2.2.so /usr/lib/jni/libgdalalljni.so
ENV LD_LIBRARY_PATH /usr/lib/jni
