# kongyl/gdal-java:3.6.4-11-hdfs
FROM kongyl/java:openjdk-11.0.18-jdk-headless
LABEL author="kongyl"
LABEL email="kongyl@126.com"
LABEL java.version="openjdk-11.0.18-jdk-headless"
LABEL hadoop.version="3.3.5"
LABEL gdal.version="3.6.4"
ADD gdal-3.6.4.tar.gz /usr/local
ADD hadoop-3.3.5.tar.gz /usr/local
RUN \
  # install dep
  mv /etc/apt/sources.list /etc/apt/sources.list.bak && \
  echo "deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ jammy main restricted universe multiverse" >>/etc/apt/sources.list && \
  echo "deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ jammy-security main restricted universe multiverse" >>/etc/apt/sources.list && \
  echo "deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ jammy-updates main restricted universe multiverse" >>/etc/apt/sources.list && \
  echo "deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ jammy-proposed main restricted universe multiverse" >>/etc/apt/sources.list && \
  echo "deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ jammy-backports main restricted universe multiverse" >>/etc/apt/sources.list && \
  apt-get update && \
  apt-get install -y --no-install-recommends build-essential cmake libproj-dev swig ant && \
  ln -s $JAVA_HOME/lib/server/libjvm.so /usr/lib/libjvm.so && \
  # compile gdal
  mkdir /usr/local/gdal-3.6.4/build && \
  cd /usr/local/gdal-3.6.4/build && \
  cmake -DCMAKE_INSTALL_PREFIX=/usr/local/gdal -DCMAKE_BUILD_TYPE=Release -DJAVA_AWT_INCLUDE_PATH=$JAVA_HOME/include -DJAVA_AWT_LIBRARY=$JAVA_HOME/lib/server/libjvm.so -DHDFS_INCLUDE_DIR=/usr/local/hadoop-3.3.5/include -DHDFS_LIBRARY=/usr/local/hadoop-3.3.5/lib/native/libhdfs.so .. && \  
  cmake --build . && \
  cmake --build . --target install && \
  ln -s /usr/local/gdal/lib/libgdal.so.32.3.6.4 /usr/lib/libgdal.so.32 && \
  ln -s /usr/local/hadoop-3.3.5/lib/native/libhdfs.so.0.0.0 /usr/lib/libhdfs.so.0.0.0 && \
  # clean
  cd / && \
  rm -rf /usr/local/gdal-3.6.4 && \  
  apt-get remove -y build-essential cmake ant && \
  apt-get autoremove -y && \
  apt-get clean && \
  rm -rf /var/cache/apt/* && \
  rm -rf /var/lib/apt/lists/*
ENV HADOOP_HOME=/usr/local/hadoop-3.3.5
ENV LD_LIBRARY_PATH=$HADOOP_HOME/lib/native:/usr/local/gdal/share/java
ENV CLASSPATH=$CLASSPATH:$HADOOP_HOME/etc/hadoop:$HADOOP_HOME/share/hadoop/common/*:$HADOOP_HOME/share/hadoop/common/lib/*:$HADOOP_HOME/share/hadoop/hdfs/*
