# kongyl/gdal-java:3.8.4-jdk21
FROM kongyl/java:openjdk-21.0.7-jdk-headless
LABEL author="kongyl"
LABEL email="kongyl@126.com"
LABEL version="3.8.4-jdk21"
RUN \
  rm -f /etc/apt/sources.list.d/ubuntu.sources && \
  echo "Types: deb" >>/etc/apt/sources.list.d/ubuntu.sources && \
  echo "URIs: http://mirrors.tuna.tsinghua.edu.cn/ubuntu" >>/etc/apt/sources.list.d/ubuntu.sources && \
  echo "Suites: noble noble-updates noble-backports noble-security" >>/etc/apt/sources.list.d/ubuntu.sources && \
  echo "Components: main restricted universe multiverse" >>/etc/apt/sources.list.d/ubuntu.sources && \
  echo "Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg" >>/etc/apt/sources.list.d/ubuntu.sources && \
  apt-get update && \
  apt-get install -y gdal-bin && \
  apt-get autoremove -y && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*
ADD libgdalalljni-3.8.4.so /usr/lib/jni/libgdalalljni.so
ENV LD_LIBRARY_PATH=/usr/lib/jni
