# kongyl/gdal-java:3.8.4-jdk17
FROM kongyl/java:openjdk-17.0.10-jdk-headless
LABEL author="kongyl"
LABEL email="kongyl@126.com"
LABEL version="3.8.4-jdk17"
RUN \
  mv /etc/apt/sources.list /etc/apt/sources.list.bak && \
  echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm main contrib non-free" >>/etc/apt/sources.list && \
  echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm-updates main contrib non-free" >>/etc/apt/sources.list && \
  echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm-backports main contrib non-free" >>/etc/apt/sources.list && \
  echo "deb http://security.debian.org/debian-security bookworm-security main contrib non-free" >>/etc/apt/sources.list && \
  apt-get update && \
  apt-get install -y gdal-bin && \
  apt-get autoremove -y && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*
ADD libgdalalljni-3.8.4.so /usr/lib/jni/libgdalalljni.so
ENV LD_LIBRARY_PATH /usr/lib/jni
