# registry.cn-beijing.aliyuncs.com/kongyl/gdal-java:3.6.2-jdk8
FROM registry.cn-beijing.aliyuncs.com/kongyl/java:oracle-jdk-1.8.0_381
LABEL author="kongyl"
LABEL email="kongyl@126.com"
LABEL version="3.6.2-jdk8"
# GDAL
RUN \
  echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm main contrib non-free non-free-firmware" >>/etc/apt/sources.list && \
  echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm-updates main contrib non-free non-free-firmware" >>/etc/apt/sources.list && \
  echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm-backports main contrib non-free non-free-firmware" >>/etc/apt/sources.list && \
  echo "deb http://security.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware" >>/etc/apt/sources.list && \
  apt-get update && \
  apt-get install -y --no-install-recommends gdal-bin && \
  apt-get autoremove -y && \  
  apt-get clean && \
  rm -rf /var/cache/apt/* && \
  rm -rf /var/lib/apt/lists/*
ADD libgdalalljni-3.6.2.so /usr/lib/jni/libgdalalljni.so
ENV LD_LIBRARY_PATH /usr/lib/jni

