# kongyl/gdal-java:3.6.2-jdk17
FROM kongyl/java:openjdk-17.0.13-jdk-headless
LABEL author="kongyl"
LABEL email="kongyl@126.com"
LABEL version="3.6.2-jdk17"
RUN \
  rm -f /etc/apt/sources.list.d/debian.sources && \
  echo "Types: deb" >>/etc/apt/sources.list.d/debian.sources && \
  echo "URIs: http://mirrors.tuna.tsinghua.edu.cn/debian" >>/etc/apt/sources.list.d/debian.sources && \
  echo "Suites: bookworm bookworm-updates bookworm-backports" >>/etc/apt/sources.list.d/debian.sources && \
  echo "Components: main contrib" >>/etc/apt/sources.list.d/debian.sources && \
  echo "Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg" >>/etc/apt/sources.list.d/debian.sources && \
  echo "" >>/etc/apt/sources.list.d/debian.sources && \
  echo "Types: deb" >>/etc/apt/sources.list.d/debian.sources && \
  echo "URIs: https://mirrors.tuna.tsinghua.edu.cn/debian-security" >>/etc/apt/sources.list.d/debian.sources && \
  echo "Suites: bookworm-security" >>/etc/apt/sources.list.d/debian.sources && \
  echo "Components: main contrib" >>/etc/apt/sources.list.d/debian.sources && \
  echo "Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg" >>/etc/apt/sources.list.d/debian.sources && \
  apt-get update && \
  apt-get install -y gdal-bin && \
  apt-get autoremove -y && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*
ADD libgdalalljni-3.6.2.so /usr/lib/jni/libgdalalljni.so
ENV LD_LIBRARY_PATH=/usr/lib/jni
